openapi: 3.0.0
info:
  title: M&A Earn-out API
  version: 1.0.0
  description: |
    # M&A Earn-out Management API

    This API powers a decentralized M&A earn-out tracking and settlement system built on **Sui blockchain**, **Walrus decentralized storage**, and **Seal encryption**.

    ## System Overview

    The system enables buyers (acquirers), sellers, and auditors to:
    - Create and manage earn-out agreements on-chain
    - Store encrypted financial documents on Walrus
    - Track KPIs and verify calculations transparently
    - Execute settlements automatically based on audited KPIs

    ## Technology Stack

    - **Blockchain**: Sui Network (smart contracts in Move)
    - **Storage**: Walrus (decentralized file storage)
    - **Encryption**: Seal (role-based access control)
    - **Frontend**: Next.js with @mysten/dapp-kit

    ## Key Concepts

    ### Deal
    An on-chain earn-out agreement with defined periods, KPI types, and payout formulas. Each deal has three roles:
    - **Buyer**: Creates deal, uploads data, proposes KPIs, executes settlements
    - **Seller**: Monitors progress, receives payouts
    - **Auditor**: Verifies data, attests KPIs

    ### Period
    A time range (e.g., fiscal year) with specific KPI targets and earn-out formulas. Each period progresses through stages:
    1. Data Collection (buyer uploads financial documents)
    2. KPI Proposal (buyer proposes calculated KPI)
    3. KPI Attestation (auditor verifies and approves)
    4. Settlement (buyer executes payout to seller)

    ### Walrus Blobs
    Encrypted financial documents stored on Walrus network. Access controlled by Seal policy on Sui blockchain.

    ### KPI (Key Performance Indicator)
    Metrics like revenue, EBITDA, or custom metrics that determine earn-out amounts according to on-chain formulas.

    ## Authentication

    This API uses a **tiered authentication system** designed for optimal UX and security:

    ### Level 1: Read Operations (Address-only Authentication)

    **For**: GET endpoints (listing deals, viewing dashboard, querying data)

    **Requirements**:
    - `X-Sui-Address`: User's Sui wallet address (0x + 64 hex characters)

    **Security**:
    - Backend validates address format
    - Backend filters all queries to only return data accessible to the provided address
    - Works with all wallet types (traditional wallets + zkLogin)

    **No signature required** - provides frictionless browsing experience after wallet connection.

    ### Level 2: Write Operations (On-Chain Signature)

    **For**: POST/PUT endpoints that modify blockchain state (create deal, upload files, submit audit)

    **Requirements**:
    - `X-Sui-Address`: User's Sui wallet address

    **Security**:
    - API returns unsigned transaction bytes
    - Frontend prompts user to sign transaction with their wallet
    - Transaction is executed on-chain with full cryptographic verification
    - Move smart contracts enforce all permissions and business logic

    **User signs once per transaction** - only when making important state changes.

    ### Why This Design?

    - **Better UX**: No signature prompts for read operations
    - **zkLogin Compatible**: Works with OAuth-based wallets (Google, Facebook)
    - **Secure**: Write operations protected by blockchain signatures
    - **Simple**: Stateless backend, no session management

    ## Workflow

    1. **Setup**: Buyer creates deal and sets earn-out parameters
    2. **Data Upload**: Buyer uploads encrypted financial docs to Walrus (via upload relay)
    3. **KPI Proposal**: After period ends, buyer proposes KPI value
    4. **Verification**: Auditor decrypts docs, verifies calculations, attests KPI
    5. **Settlement**: Buyer executes settlement, funds transferred to seller

    ## API Organization

    - **Deal Management**: Create and manage earn-out deals
    - **Parameters**: Configure earn-out formulas and periods
    - **Walrus**: Upload relay for encrypted file storage
    - **Timeline**: View data submission history
    - **KPI Management**: Propose and attest KPIs
    - **Settlement**: Execute earn-out payments
    - **Dashboard**: Aggregated view of deal status

  contact:
    name: API Support
    url: https://github.com/yourusername/walrus-hackathon
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://localhost:3000/api/v1
    description: Development server (API v1)
  - url: https://ma-earnout-2025walrushackathon.vercel.app/api/v1
    description: Production server (API v1)

tags:
  - name: Deals
    description: |
      Deal-related endpoints including creation, listing, dashboard, and blob management.

      All operations under /deals/* route for managing M&A earn-out agreements on Sui blockchain.
  - name: Walrus
    description: |
      Walrus decentralized storage endpoints for file upload and download.

      All operations under /walrus/* route with upload/download relays and Seal encryption integration.
  - name: Nautilus
    description: |
      Nautilus KPI calculation endpoints.

      All operations under /nautilus/* route for automated KPI calculations based on financial data.
  - name: Health
    description: |
      API health check endpoint.

      Returns the operational status of the API service.

components:
  securitySchemes:
    Level1Auth:
      type: apiKey
      in: header
      name: X-Sui-Address
      description: |
        **Authentication Level 1: Read Operations**

        Sui wallet address of the authenticated user.

        **Format**: Must be a valid Sui address (0x + 64 hex characters)

        **Example**: `0xabcd1234567890abcdef1234567890abcdef1234567890abcdef1234567890`

        **Used for**: GET endpoints (listing, querying, viewing data)

        **Security**: Backend filters all results to only return data accessible to this address.

        **No signature required** - this enables frictionless data browsing after wallet connection.

    Level2Auth:
      type: apiKey
      in: header
      name: X-Sui-Address
      description: |
        **Authentication Level 2: Write Operations**

        Sui wallet address of the user initiating the transaction.

        **Format**: Must be a valid Sui address (0x + 64 hex characters)

        **Example**: `0xabcd1234567890abcdef1234567890abcdef1234567890abcdef1234567890`

        **Used for**: POST/PUT endpoints that create or modify blockchain state

        **Security Flow**:
        1. API validates address format
        2. API builds unsigned transaction bytes
        3. API returns transaction to frontend
        4. User signs transaction in wallet (cryptographic proof of identity)
        5. Transaction is executed on-chain with full signature verification

        **Transaction signing happens in wallet** - API does not verify signatures directly.

  schemas: {}

security:
  - Level1Auth: []
