openapi: 3.0.0
info:
  title: M&A Earn-out API
  version: 1.0.0
  description: |
    # M&A Earn-out Management API

    This API powers a decentralized M&A earn-out tracking and settlement system built on **Sui blockchain**, **Walrus decentralized storage**, and **Seal encryption**.

    ## System Overview

    The system enables buyers (acquirers), sellers, and auditors to:
    - Create and manage earn-out agreements on-chain
    - Store encrypted financial documents on Walrus
    - Track KPIs and verify calculations transparently
    - Execute settlements automatically based on audited KPIs

    ## Technical Innovation Highlights

    This platform demonstrates several key technical innovations for the Walrus Hackathon:

    **1. Walrus as Core Storage Layer**
    - Financial documents stored on Walrus decentralized network, not centralized servers
    - Blob IDs registered on Sui blockchain for immutable proof of data
    - No single point of failure or censorship risk

    **2. Hybrid Encryption Architecture**
    - Client-side encryption: Files encrypted in browser before upload (zero-knowledge)
    - Server-side encryption: Backend encrypts for simplified UX
    - Both modes use Seal for role-based access control (buyer, seller, auditor)

    **3. Upload Relay Optimization**
    - Single API call handles: Walrus upload + Seal encryption + on-chain registration
    - Reduces 2000+ frontend requests to 1 backend operation
    - Improves UX and reduces gas costs

    **4. Tiered Authentication System**
    - Level 1 (Read): Address-only authentication, no signature required
    - Level 2 (Write): Returns unsigned transactions for wallet signing
    - Enables zkLogin compatibility (OAuth wallets) and frictionless browsing

    **5. TEE Integration**
    - Nautilus Trusted Execution Environment for verifiable KPI computation
    - 144-byte cryptographic attestation proves calculation integrity
    - TEE fetches data from Walrus, computes KPI, signs result with Ed25519

    ## Technology Stack

    - **Blockchain**: Sui Network (smart contracts in Move)
    - **Storage**: Walrus Protocol (decentralized blob storage)
    - **Encryption**: Mysten Seal (role-based access control)
    - **TEE**: Nautilus (verifiable computation)
    - **Frontend**: Next.js 16 with @mysten/dapp-kit

    ## Key Concepts

    ### Deal
    An on-chain earn-out agreement with defined periods, KPI types, and payout formulas. Each deal has three roles:
    - **Buyer**: Creates deal, uploads data, proposes KPIs, executes settlements
    - **Seller**: Monitors progress, receives payouts
    - **Auditor**: Verifies data, attests KPIs

    ### Period
    A time range (e.g., fiscal year) within a deal where KPIs are tracked and verified.

    ### Walrus Blobs
    Encrypted financial documents stored on Walrus network, with blob IDs registered on-chain for immutable proof.

    ### KPI (Key Performance Indicator)
    Metrics like revenue, EBITDA, or custom calculations that determine earn-out amounts.

    ## Authentication

    **Tiered Authentication System** designed for optimal UX and security:

    **Level 1 (Read Operations)**
    - For: GET endpoints (listing, querying, viewing data)
    - Requires: `X-Sui-Address` header (wallet address)
    - Security: Backend filters results by address, no signature needed
    - Benefit: Frictionless browsing after wallet connection

    **Level 2 (Write Operations)**
    - For: POST/PUT endpoints (create deal, upload files, KPI calculations)
    - Requires: `X-Sui-Address` header
    - Flow: API returns unsigned transaction → User signs in wallet → Transaction executed on-chain
    - Security: Full cryptographic verification via blockchain signatures
    - Benefit: zkLogin compatible, user controls private keys

    ## Data Flow

    1. Buyer creates deal on Sui blockchain with defined roles (buyer, seller, auditor)
    2. Buyer uploads encrypted financial documents to Walrus via upload relay
    3. Backend registers Walrus blob IDs on-chain for immutable proof
    4. Auditor retrieves and decrypts blobs from Walrus to verify data
    5. TEE computes KPI from Walrus data with cryptographic attestation
    6. Smart contract executes settlement based on attested KPI

    ## API Organization

    - **Health**: System health check
    - **Deals**: Create and query earn-out agreements
    - **Dashboard**: Aggregated deal metrics and period summaries
    - **Blobs**: Query registered Walrus blob references
    - **Walrus**: Upload/download encrypted files to Walrus network
    - **Nautilus**: TEE-based KPI calculation with attestation

  contact:
    name: API Support
    url: https://github.com/yourusername/walrus-hackathon
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://localhost:3000/api/v1
    description: Development server (API v1)
  - url: https://ma-earnout-2025walrushackathon.vercel.app/api/v1
    description: Production server (API v1)

tags:
  - name: Health
    description: API health check endpoint. Returns operational status.

  - name: Deals
    description: |
      Create and query M&A earn-out agreements on Sui blockchain.
      Includes deal creation, listing by role, single deal retrieval, dashboard metrics, and blob reference queries.

  - name: Walrus
    description: |
      Decentralized storage operations using Walrus Protocol.
      Upload relay handles encryption (client/server modes) + Walrus upload + on-chain blob registration.
      Download relay retrieves encrypted blobs for client-side decryption.

  - name: Nautilus
    description: |
      TEE-based KPI calculation with cryptographic attestation.
      Nautilus computes KPIs from Walrus data and generates 144-byte Ed25519 signed attestations.

components:
  securitySchemes:
    Level1Auth:
      type: apiKey
      in: header
      name: X-Sui-Address
      description: |
        Level 1 Authentication for Read Operations (GET endpoints)

        Format: Valid Sui address (0x + 64 hex characters)
        Example: `0xabcd1234567890abcdef1234567890abcdef1234567890abcdef1234567890`

        No signature required. Backend filters results by this address for access control.
        Enables frictionless browsing and zkLogin compatibility.

    Level2Auth:
      type: apiKey
      in: header
      name: X-Sui-Address
      description: |
        Level 2 Authentication for Write Operations (POST/PUT endpoints)

        Format: Valid Sui address (0x + 64 hex characters)

        Security Flow:
        1. API validates address and builds unsigned transaction bytes
        2. API returns transaction to frontend
        3. User signs transaction in wallet
        4. Transaction executed on-chain with full cryptographic verification

        Signature verification happens on Sui blockchain, not in API.

  schemas: {}

security:
  - Level1Auth: []
